version: '3.7'

services:


  front:
    build: ./proyecto
    depends_on:
      - db
    volumes:
      - ./proyecto:/usr/share/nginx/html
    networks:
      - redproyecto

  generador:
    build: ./generadorDatos
    command: sh -c 'while true; do php /app/generadorDatos.php; sleep 10; done'
    volumes:
      - ./generadorDatos:/app
    depends_on:
      - db
    networks:
      - redproyecto

  laravel1:
    build: ./laravel
    image: laravel.prod
    depends_on:
      - db
    networks:
      - redproyecto

  laravel2:
    build: ./laravel
    image: laravel.prod
    depends_on:
      - db
    networks:
      - redproyecto
  db:
    image: mysql
    command: --max_allowed_packet=325058560
    environment: 
      MYSQL_ROOT_PASSWORD: reto
      MYSQL_USER: reto
      MYSQL_DATABASE: reto
      MYSQL_PASSWORD: reto
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
      - /mysql:/var/lib/mysql

    networks:
      - redproyecto
    ports:
      - 3306:3306


  phpmyadmin:
          depends_on:
              - db
          image: 'phpmyadmin/phpmyadmin:latest'
          restart: always
          environment:
              PMA_HOST: db
              PMA_PORT: 3306
              PMA_USER: 'reto'
              PMA_PASSWORD: 'reto'
          networks:
              - redproyecto
          ports:
              - 83:80
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - redproyecto
    depends_on:
      - laravel1
      - laravel2
networks:
    redproyecto:
        driver: bridge
